### ISSUE TITLE
Adblocking does not work consistently [CRITICAL]

### ISSUE THREAD

**Issue by saagarjha** [jusleg/OpenAdblock#27]
Adblocking only works sometimes

**Comment by lbalogh** [comment]
Hi,

If I use the filters here :

https://github.com/krishkumar/BlockParty/blob/master/RediffBlock/blockerList.json

Blocking works well and consistently. If I try the filters you pushed 2 days ago (https://github.com/jusleg/OpenAdblock/blob/master/Open%20Adblock/Adblock%20Content%20Blocker/blockerList.json) it doesn't seem to work.

Also I tried to convert the MVPS host file (http://winhelp2002.mvps.org/hosts.txt) to json format, which you can find here : https://dl.dropboxusercontent.com/u/6766348/blockerList.json, but it doesn't seem to block anything neither.

Is there a limit to the json filters file size or number of filters ?

**Comment by jusleg** [comment]
I do not think that we went over the limit if a limit exists. Adios content blocker has 150 000+ blocked sites. I may have messed up the formating on the new list...

**Comment by jusleg** [comment]
for the moment we will just use block party's list. I am confident that I screwed up the json

**Comment by lbalogh** [comment]
Is there a way to debug the code in ActionRequestHandler.swift ? If I run the extension in the simulator, breakpoints are not triggered and print("...") doesn't output anything in the debug console

**Comment by jusleg** [comment]
That I do not have no clue. We are experiencing the same thing...

**Comment by lbalogh** [comment]
Just found that you have to start the app from Xcode, then you can attach to the "Adblock Content Blocker" process from the Debug menu of Xcode (I'm doing this from BlockParty, but should be the same with your projet).

"print" doesn't work, but you can set breakpoints and they are triggered

**Comment by saagarjha** [comment]
I'm not at my computer, but my phone has come content blocker crash logs. I have heard that we can have up to 50,000 blocks.

**Comment by lbalogh** [comment]
Well, I just retried your filters and it works now in the simulator, but not on the real device. I get very inconsistent results, as stated in your title

**Comment by saagarjha** [comment]
Hmm...I'll try this when I get home. I found that this works in the simulator once in a while, but rarely on the device.

**Comment by saagarjha** [comment]
The BlockParty list fails to work…did you do anything special?

**Comment by lbalogh** [comment]
What do you mean by fail to load ? Do you get an error or something ?

When doing some tests, I sometimes have to restart my device (real or simulator) to make changes apply. Yesterday I uninstalled BlockParty, and even after killing Safari with cleared cache, it was still blocking ads (with no blocker installed) :/

**Comment by saagarjha** [comment]
i.e. It doesn't do any blocking.

**Comment by lbalogh** [comment]
Try the filters of this comment : https://github.com/krishkumar/BlockParty/issues/1#issuecomment-135748871

It's a conversion of easyList. It works for me (had to kill safari, clear cache, and reboot my device)

**Comment by saagarjha** [comment]
I have recreated the project and it seems to work now.

**Comment by saagarjha** [comment]
I have isolated the issue to the new JSON file. The moment it is used, the whole thing breaks, permanently.
