### ISSUE TITLE
Failed to Code Sign "Open AdblockUITests"

### ISSUE THREAD

**Issue by chdsbd** [jusleg/OpenAdblock#28]
I changed the names mentioned in the README but I got this error when attempt to build for the phone.
<img width="451" alt="error" src="https://cloud.githubusercontent.com/assets/1929960/9559858/650fbd74-4dca-11e5-9648-0531d795cd17.png">

**Comment by saagarjha** [comment]
Try clicking fix issue. BTW, Open Adblock has moved: https://github.com/saagarjha/OpenAdblock

**Comment by chdsbd** [comment]
Yeah, I tried that and it didn't fix it. It throws this error.
I will try using the current version of Open Adblock.

<img width="443" alt="error2" src="https://cloud.githubusercontent.com/assets/1929960/9559935/c379b048-4dcc-11e5-98a9-81b413c8a4fe.png">

**Comment by chdsbd** [comment]
I used https://github.com/saagarjha/OpenAdblock and followed the provided instructions and that worked. Although after Xcode finished fixing the issues I did need to uncheck the original App Group.
